language: cpp

os:
- linux
- osx

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - g++-4.8
#    - g++-4.8-multilib
#    - gcc-multilib
#    - libusb-1.0-0:i386
#    - libusb-1.0-0-dev
#    - libudev-dev

before_install:
# fix numerous error msgs like:
#  suppress 'shell_session_update' error https://github.com/travis-ci/travis-ci/issues/6307
#  https://github.com/travis-ci/travis-ci/issues/6307
- rvm get stable

script:
    - gcc -o cpp-struct-tsts cpp-struct-tsts.cpp
    - zip cpp-struct-tsts-${TRAVIS_OS_NAME}.zip cpp-struct-tsts
    # 's3' provider needs a directory to send, so make one
    - mkdir build
    - mv *zip build

before_deploy:
    - DFILE1=cpp-struct-tsts.zip
    #- DFILE2=$(ls commandline/blink1-lib*zip)
    #- DFILE3=$(ls commandline/blink1-tiny-server*zip)

deploy:
  skip_cleanup: true
  provider: s3
  # You can refer to environment variables from Travis repo settings
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: todtravistest2
  # 's3' provider doesn't do "file:" and only copies a directory, so set that
  local_dir: build
