os: unstable
#environment:
#  matrix:
#    - MSYSTEM : MINGW64
#      MBITS: 64
#      MARCH: x86_64
#    - MSYSTEM : MINGW32
#      MBITS: 32
#      MARCH: i686

platform:
- x86
- x64

install:
#set "PATH=C:\msys64\usr\bin;C:\msys64\mingw%MBITS%\bin;%PATH%"
#- ps: $env:Path += ";C:\MinGW\bin;"
#- ps: $env:Path += ";C:\MinGW\msys\1.0\bin";
- ps: $env:Path = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\bin;" + $env:Path
- set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
#- ps: $env:Path += ";C:\msys64\mingw64\bin;C:\msys64\usr\bin\"
- ps: if ( $env:Platform -eq "x64" ) {
        $env:Path = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;" + $env:Path
      } else {
        $env:Path = "C:\msys64\mingw32\bin;C:\msys64\usr\bin;" + $env:Path
      }
- ps: env

build_script:
- ps: env
- ps: gcc --version
- ps: uname -s
- ps: pacman -S zip --noconfirm
#- ps: zip -h
- ps: gcc -o cpp-struct-tsts.exe cpp-struct-tsts.cpp
- ps: zip -r cpp-struct-tsts-Win_$env:Platform.zip cpp-struct-tsts.exe

artifacts:
    - path: cpp-struct-tsts-Win_$env:Platform.zip
      name: proggie

deploy:
  provider: S3
  access_key_id:
      secure: k+MjsHqRpP9DkNI3S+8W5CedlW+P6MbL2I+s9UKfH2w=
  secret_access_key:
      secure: QiRehApfnik9m7tDFwssuTgeLlcGO3LrnJvL6apGxESPOtBt/8beI6ebxczBBB99
  bucket: todtravistest2
  #artifact: cpp-struct-tsts-Win_$env:Platform.zip
#    artifacdt: proggie
#    provider: GitHub
#    auth_token:
#        secure: VYJPed/ilAHFpd7S0zW/C2U1jVqayW5QFBitwBqralJlKlgAPW6n1L1VUIOJswiW
#    draft: false
#    prerelease: false
#    on:
#        appveyor_repo_tag: true
