os: unstable
#environment:
#  matrix:
#    - MSYSTEM : MINGW64
#      MBITS: 64
#      MARCH: x86_64
#    - MSYSTEM : MINGW32
#      MBITS: 32
#      MARCH: i686

platform:
- x86
- x64

install:
#set "PATH=C:\msys64\usr\bin;C:\msys64\mingw%MBITS%\bin;%PATH%"
#- ps: $env:Path += ";C:\MinGW\bin;"
- ps: $env:Path += ";C:\MinGW\msys\1.0\bin";
- ps: $env:Path = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\bin;" + $env:Path
#- set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%
#- ps: $env:Path += ";C:\msys64\mingw64\bin;C:\msys64\usr\bin\"
- ps: if ( $env:Platform -eq "x64" ) {
        $env:Path = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;" + $env:Path
      } else {
        $env:Path = "C:\msys64\mingw32\bin;C:\msys64\usr\bin;" + $env:Path
      }
- ps: env

build_script:
- ps: env
- ps: gcc --version
- ps: uname -s
- ps: zip -h
#- ps: dir C:\msys64
#- ps: dir C:\msys64\usr\bin
#- ps: dir C:\msys64\mingw64\bin
#- ps: dir C:\msys64\mingw32\bin
- ps: gcc -o cpp-struct-tsts.exe cpp-struct-tsts.cpp

artifacts:
    - path: 'cpp-struct-tsts.exe'
      name: proggie

deploy:
    artifacdt: proggie
    provider: GitHub
    auth_token:
        secure: VYJPed/ilAHFpd7S0zW/C2U1jVqayW5QFBitwBqralJlKlgAPW6n1L1VUIOJswiW
    draft: false
    prerelease: false
    #on:
    #    appveyor_repo_tag: true
